### ISSUE TITLE
Does this correspond to the gh-pages?

### ISSUE THREAD

**Issue by syui** [m2w/talaria#12]
url : `https://user.github.io/gh-pages`
branch : `gh-pages`

**Comment by m2w** [comment]
I'm not quite sure what you mean. I presume you are asking if you can use talaria in combination with github pages. You can, for an example setup, checkout [m2w/m2w.github.com](https://github.com/m2w/m2w.github.com), where I'm using talaria in combination with jekyll.

_Side note:_ I would highly recommend that you use the gist backend over the commit-based backend. In the upcoming rewrite (coming soon™) I'm actually completely dropping support for commit-based commenting, as it runs into the github API rate limit too fast.

I hope that kind of answers your question, if not, feel free to ask :)

**Comment by syui** [comment]
Thanks you.
