### ISSUE TITLE
Config for no permalink

### ISSUE THREAD

**Issue by syui** [m2w/talaria#13]
Do you know the configuration of no permalink?

For example `http://localhost/post/2016-01-01-creating-a-new-theme/`, What should I do?

> talaria.js

```js
var CONFIG = {},
        DEFAULTS = {
          PAGINATION_SCHEME: /\/post\d+\//,
          PERMALINK_STYLE: /[\.\w\-_:\/]+\/(\d+)\/(\d+)\/(\d+)\/([\w\-\.]+)$/
```

**Comment by m2w** [comment]
If I understand your question correctly, you want to match permalinks that look like `http://localhost/post/2016-01-01-creating-a-new-theme/`?

**Note** that this is only necessary for the *commit-message* based approach (which I consider deprecated).
In that case you will have to set `PERMALINK_STYLE` to a regex that will match those kinds of URLs, check out the [docs](https://github.com/m2w/talaria#commit-backend-specific-settings)

For the other backends, you provide the permalink yourself as part of the mappings.

**Comment by syui** [comment]
> If I understand your question correctly, you want to match permalinks that look like http://localhost/post/2016-01-01-creating-a-new-theme/?

yes, But, the following configuration was invalid.

> talaria.js

```js
var CONFIG = {},
        DEFAULTS = {
          PAGINATION_SCHEME: "",
          PERMALINK_STYLE: ""
```

**Comment by m2w** [comment]
Well, an empty regex is not going to match something like `http://localhost/post/2016-01-01-creating-a-new-theme/`, you will need to provide an appropriate regex to match. For details on how the regex is used, please check out the src, starting [here](https://github.com/m2w/talaria/blob/master/lib/talaria.js#L28) and [here](https://github.com/m2w/talaria/blob/master/lib/talaria.js#L47).

**Comment by syui** [comment]
Thanks for your advice.
